name: Metrics
on:
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: SammCheese
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          config_order: base.header, isocalendar, base.activity+community, base.repositories, notable, followup, languages, topics, activity
